// GType fundamental types
export const G_TYPE_INVALID = 0 << 2;
export const G_TYPE_NONE = 1 << 2;
export const G_TYPE_INTERFACE = 2 << 2;
export const G_TYPE_CHAR = 3 << 2;
export const G_TYPE_UCHAR = 4 << 2;
export const G_TYPE_BOOLEAN = 5 << 2;
export const G_TYPE_INT = 6 << 2;
export const G_TYPE_UINT = 7 << 2;
export const G_TYPE_LONG = 8 << 2;
export const G_TYPE_ULONG = 9 << 2;
export const G_TYPE_INT64 = 10 << 2;
export const G_TYPE_UINT64 = 11 << 2;
export const G_TYPE_ENUM = 12 << 2;
export const G_TYPE_FLAGS = 13 << 2;
export const G_TYPE_FLOAT = 14 << 2;
export const G_TYPE_DOUBLE = 15 << 2;
export const G_TYPE_STRING = 16 << 2;
export const G_TYPE_POINTER = 17 << 2;
export const G_TYPE_BOXED = 18 << 2;
export const G_TYPE_PARAM = 19 << 2;
export const G_TYPE_OBJECT = 20 << 2;
export const G_TYPE_VARIANT = 21 << 2;

// GTK Orientation enum
export const GTK_ORIENTATION_HORIZONTAL = 0;
export const GTK_ORIENTATION_VERTICAL = 1;

// Adwaita color scheme enum
export const ADW_COLOR_SCHEME_DEFAULT = 0;
export const ADW_COLOR_SCHEME_FORCE_LIGHT = 1;
export const ADW_COLOR_SCHEME_FORCE_DARK = 2;

// GTK Align enum
export const GTK_ALIGN_FILL = 0;
export const GTK_ALIGN_START = 1;
export const GTK_ALIGN_END = 2;
export const GTK_ALIGN_CENTER = 3;
export const GTK_ALIGN_BASELINE = 4;

// GTK SelectionMode enum
export const GTK_SELECTION_NONE = 0;
export const GTK_SELECTION_SINGLE = 1;
export const GTK_SELECTION_BROWSE = 2;
export const GTK_SELECTION_MULTIPLE = 3;

export const GTK_APPLICATION_INHIBIT_LOGOUT = 1;
export const GTK_APPLICATION_INHIBIT_SWITCH = 2;
export const GTK_APPLICATION_INHIBIT_SUSPEND = 4;
export const GTK_APPLICATION_INHIBIT_IDLE = 8;

// Response appearance constants
export const ADW_RESPONSE_DEFAULT = 0;
export const ADW_RESPONSE_SUGGESTED = 1;
export const ADW_RESPONSE_DESTRUCTIVE = 2;

// GtkLicense
export const GTK_LICENSE_UNKNOWN = 0;
export const GTK_LICENSE_CUSTOM = 1;
export const GTK_LICENSE_GPL_2_0 = 2;
export const GTK_LICENSE_GPL_3_0 = 3;
export const GTK_LICENSE_LGPL_2_1 = 4;
export const GTK_LICENSE_LGPL_3_0 = 5;
export const GTK_LICENSE_BSD = 6;
export const GTK_LICENSE_MIT_X11 = 7;
export const GTK_LICENSE_ARTISTIC = 8;
export const GTK_LICENSE_GPL_2_0_ONLY = 9;
export const GTK_LICENSE_GPL_3_0_ONLY = 10;
export const GTK_LICENSE_LGPL_2_1_ONLY = 11;
export const GTK_LICENSE_LGPL_3_0_ONLY = 12;
export const GTK_LICENSE_AGPL_3_0 = 13;
export const GTK_LICENSE_AGPL_3_0_ONLY = 14;
export const GTK_LICENSE_BSD_3 = 15;
export const GTK_LICENSE_APACHE_2_0 = 16;
export const GTK_LICENSE_MPL_2_0 = 17;

// Style Provider Priority
export const GTK_STYLE_PROVIDER_PRIORITY_FALLBACK = 1;
export const GTK_STYLE_PROVIDER_PRIORITY_THEME = 200;
export const GTK_STYLE_PROVIDER_PRIORITY_SETTINGS = 400;
export const GTK_STYLE_PROVIDER_PRIORITY_APPLICATION = 600;
export const GTK_STYLE_PROVIDER_PRIORITY_USER = 800;

// GApplicationFlags
export const G_APPLICATION_FLAGS_NONE = 0;
export const G_APPLICATION_IS_SERVICE = 1 << 0;
export const G_APPLICATION_IS_LAUNCHER = 1 << 1;
export const G_APPLICATION_HANDLES_OPEN = 1 << 2;
export const G_APPLICATION_HANDLES_COMMAND_LINE = 1 << 3;
export const G_APPLICATION_SEND_ENVIRONMENT = 1 << 4;
export const G_APPLICATION_NON_UNIQUE = 1 << 5;
export const G_APPLICATION_CAN_OVERRIDE_APP_ID = 1 << 6;
export const G_APPLICATION_ALLOW_REPLACEMENT = 1 << 7;
export const G_APPLICATION_REPLACE = 1 << 8;

// Unix Signals
export const SIGINT = 2;
export const SIGTERM = 15;

// GPriority
export const G_PRIORITY_DEFAULT = 0;
export const G_PRIORITY_HIGH = -100;
export const G_PRIORITY_HIGH_IDLE = 100;
export const G_PRIORITY_DEFAULT_IDLE = 200;
export const G_PRIORITY_LOW = 300;

// Export constants objects
export const Orientation = {
  HORIZONTAL: GTK_ORIENTATION_HORIZONTAL,
  VERTICAL: GTK_ORIENTATION_VERTICAL,
};

export const Align = {
  FILL: GTK_ALIGN_FILL,
  START: GTK_ALIGN_START,
  END: GTK_ALIGN_END,
  CENTER: GTK_ALIGN_CENTER,
  BASELINE: GTK_ALIGN_BASELINE,
};

export const SelectionMode = {
  NONE: GTK_SELECTION_NONE,
  SINGLE: GTK_SELECTION_SINGLE,
  BROWSE: GTK_SELECTION_BROWSE,
  MULTIPLE: GTK_SELECTION_MULTIPLE,
};

export const License = {
  UNKNOWN: GTK_LICENSE_UNKNOWN,
  CUSTOM: GTK_LICENSE_CUSTOM,
  GPL_2_0: GTK_LICENSE_GPL_2_0,
  GPL_3_0: GTK_LICENSE_GPL_3_0,
  LGPL_2_1: GTK_LICENSE_LGPL_2_1,
  LGPL_3_0: GTK_LICENSE_LGPL_3_0,
  BSD: GTK_LICENSE_BSD,
  MIT_X11: GTK_LICENSE_MIT_X11,
  ARTISTIC: GTK_LICENSE_ARTISTIC,
  GPL_2_0_ONLY: GTK_LICENSE_GPL_2_0_ONLY,
  GPL_3_0_ONLY: GTK_LICENSE_GPL_3_0_ONLY,
  LGPL_2_1_ONLY: GTK_LICENSE_LGPL_2_1_ONLY,
  LGPL_3_0_ONLY: GTK_LICENSE_LGPL_3_0_ONLY,
  AGPL_3_0: GTK_LICENSE_AGPL_3_0,
  AGPL_3_0_ONLY: GTK_LICENSE_AGPL_3_0_ONLY,
  BSD_3: GTK_LICENSE_BSD_3,
  APACHE_2_0: GTK_LICENSE_APACHE_2_0,
  MPL_2_0: GTK_LICENSE_MPL_2_0,
};

export const Priority = {
  FALLBACK: GTK_STYLE_PROVIDER_PRIORITY_FALLBACK,
  THEME: GTK_STYLE_PROVIDER_PRIORITY_THEME,
  SETTINGS: GTK_STYLE_PROVIDER_PRIORITY_SETTINGS,
  APPLICATION: GTK_STYLE_PROVIDER_PRIORITY_APPLICATION,
  USER: GTK_STYLE_PROVIDER_PRIORITY_USER,
  DEFAULT: G_PRIORITY_DEFAULT,
  HIGH: G_PRIORITY_HIGH,
  HIGH_IDLE: G_PRIORITY_HIGH_IDLE,
  DEFAULT_IDLE: G_PRIORITY_DEFAULT_IDLE,
  LOW: G_PRIORITY_LOW,
};

export const ApplicationFlags = {
  NONE: G_APPLICATION_FLAGS_NONE,
  IS_SERVICE: G_APPLICATION_IS_SERVICE,
  IS_LAUNCHER: G_APPLICATION_IS_LAUNCHER,
  HANDLES_OPEN: G_APPLICATION_HANDLES_OPEN,
  HANDLES_COMMAND_LINE: G_APPLICATION_HANDLES_COMMAND_LINE,
  SEND_ENVIRONMENT: G_APPLICATION_SEND_ENVIRONMENT,
  NON_UNIQUE: G_APPLICATION_NON_UNIQUE,
  CAN_OVERRIDE_APP_ID: G_APPLICATION_CAN_OVERRIDE_APP_ID,
  ALLOW_REPLACEMENT: G_APPLICATION_ALLOW_REPLACEMENT,
  REPLACE: G_APPLICATION_REPLACE,
};

export const UnixSignal = {
  SIGINT: SIGINT,
  SIGTERM: SIGTERM,
};

export const DragAction = {
  COPY: 1,
  MOVE: 2,
  LINK: 4,
  ASK: 8,
};

export const ModifierType = {
  SHIFT_MASK: 1,
  LOCK_MASK: 2,
  CONTROL_MASK: 4,
  ALT_MASK: 8,
};

export const Key = {
  v: 118,
  o: 111,
  t: 116,
  r: 114,
  q: 113,
  w: 119,
};
